CREATE TABLE swtcw_episodes (
  id             INTEGER PRIMARY KEY,
  season         INTEGER,
  episode        INTEGER,
  title          TEXT NOT NULL,
  arc            TEXT,
  classification TEXT CHECK(classification IN ('essential','lore_light','filler')),
  watched        INTEGER NOT NULL DEFAULT 0,
  notes          TEXT,
  reviewed_at    TEXT,
  watched_at     TEXT
);

CREATE TABLE swtcw_characters (
  id         TEXT PRIMARY KEY,
  name       TEXT NOT NULL,
  sort_order INTEGER NOT NULL DEFAULT 100,
  is_seed    INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE swtcw_episode_characters (
  episode_id   INTEGER NOT NULL REFERENCES swtcw_episodes(id) ON DELETE CASCADE,
  character_id TEXT NOT NULL REFERENCES swtcw_characters(id) ON DELETE CASCADE,
  PRIMARY KEY (episode_id, character_id)
);

CREATE INDEX idx_swtcw_ep_chars_char ON swtcw_episode_characters(character_id);

-- Seed characters (sort_order in 10s for easy insertion)
INSERT INTO swtcw_characters (id, name, sort_order, is_seed) VALUES
  ('anakin',    'Anakin',   10, 1),
  ('obi-wan',   'Obi-Wan',  20, 1),
  ('ahsoka',    'Ahsoka',   30, 1),
  ('padme',     'Padmé',    40, 1),
  ('rex',       'Rex',      50, 1),
  ('maul',      'Maul',     60, 1),
  ('ventress',  'Ventress', 70, 1),
  ('dooku',     'Dooku',    80, 1),
  ('cad-bane',  'Cad Bane', 90, 1),
  ('hondo',     'Hondo',   100, 1);

-- Seed episodes (134 rows in chronological order)
INSERT INTO swtcw_episodes (id, season, episode, title, arc) VALUES
  (1,   2,    16,   'Cat and Mouse',                   'Christophsis'),
  (2,   1,    16,   'Hidden Enemy',                    'Christophsis'),
  (3,   NULL, NULL, 'The Clone Wars',                  'Christophsis'),
  (4,   3,    1,    'Clone Cadets',                    'Domino Squad'),
  (5,   3,    3,    'Supply Lines',                    'Ryloth (Setup)'),
  (6,   1,    1,    'Ambush',                          NULL),
  (7,   1,    2,    'Rising Malevolence',               'Malevolence'),
  (8,   1,    3,    'Shadow of Malevolence',            'Malevolence'),
  (9,   1,    4,    'Destroy Malevolence',              'Malevolence'),
  (10,  1,    5,    'Rookies',                         NULL),
  (11,  1,    6,    'Downfall of a Droid',              'Skytop Station'),
  (12,  1,    7,    'Duel of the Droids',               'Skytop Station'),
  (13,  1,    8,    'Bombad Jedi',                     'Nute Gunray'),
  (14,  1,    9,    'Cloak of Darkness',                'Nute Gunray'),
  (15,  1,    10,   'Lair of Grievous',                NULL),
  (16,  1,    11,   'Dooku Captured',                  'Hondo (Dooku)'),
  (17,  1,    12,   'The Gungan General',               'Hondo (Dooku)'),
  (18,  1,    13,   'Jedi Crash',                      'Lurmen'),
  (19,  1,    14,   'Defenders of Peace',               'Lurmen'),
  (20,  1,    15,   'Trespass',                        NULL),
  (21,  1,    17,   'Blue Shadow Virus',                'Blue Shadow Virus'),
  (22,  1,    18,   'Mystery of a Thousand Moons',      'Blue Shadow Virus'),
  (23,  1,    19,   'Storm over Ryloth',                'Ryloth Liberation'),
  (24,  1,    20,   'Innocents of Ryloth',              'Ryloth Liberation'),
  (25,  1,    21,   'Liberty on Ryloth',                'Ryloth Liberation'),
  (26,  2,    1,    'Holocron Heist',                   'Holocron Heist'),
  (27,  2,    2,    'Cargo of Doom',                    'Holocron Heist'),
  (28,  2,    3,    'Children of the Force',            'Holocron Heist'),
  (29,  2,    17,   'Bounty Hunters',                  NULL),
  (30,  2,    18,   'The Zillo Beast',                  'Zillo Beast'),
  (31,  2,    19,   'The Zillo Beast Strikes Back',     'Zillo Beast'),
  (32,  2,    4,    'Senate Spy',                      NULL),
  (33,  2,    5,    'Landing at Point Rain',            'Second Battle of Geonosis'),
  (34,  2,    6,    'Weapons Factory',                  'Second Battle of Geonosis'),
  (35,  2,    7,    'Legacy of Terror',                 'Second Battle of Geonosis'),
  (36,  2,    8,    'Brain Invaders',                   'Second Battle of Geonosis'),
  (37,  2,    9,    'Grievous Intrigue',                'Eeth Koth / Saleucami'),
  (38,  2,    10,   'The Deserter',                    'Eeth Koth / Saleucami'),
  (39,  2,    11,   'Lightsaber Lost',                 NULL),
  (40,  2,    12,   'The Mandalore Plot',               'Death Watch'),
  (41,  2,    13,   'Voyage of Temptation',             'Death Watch'),
  (42,  2,    14,   'Duchess of Mandalore',             'Death Watch'),
  (43,  2,    20,   'Death Trap',                      'Boba Fett'),
  (44,  2,    21,   'R2 Come Home',                    'Boba Fett'),
  (45,  2,    22,   'Lethal Trackdown',                'Boba Fett'),
  (46,  3,    5,    'Corruption',                      'Mandalore Cadets'),
  (47,  3,    6,    'The Academy',                     'Mandalore Cadets'),
  (48,  3,    7,    'Assassin',                        'Mandalore Cadets'),
  (49,  3,    2,    'ARC Troopers',                    'Kamino Invasion'),
  (50,  3,    4,    'Sphere of Influence',             NULL),
  (51,  3,    8,    'Evil Plans',                      NULL),
  (52,  1,    22,   'Hostage Crisis',                  'Hunt for Ziro'),
  (53,  3,    9,    'Hunt for Ziro',                   'Hunt for Ziro'),
  (54,  3,    10,   'Heroes on Both Sides',             'Senate Politics'),
  (55,  3,    11,   'Pursuit of Peace',                'Senate Politics'),
  (56,  2,    15,   'Senate Murders',                  NULL),
  (57,  3,    12,   'Nightsisters',                    'Nightsisters'),
  (58,  3,    13,   'Monster',                         'Nightsisters'),
  (59,  3,    14,   'Witches of the Mist',              'Nightsisters'),
  (60,  3,    15,   'Overlords',                       'Mortis'),
  (61,  3,    16,   'Altar of Mortis',                 'Mortis'),
  (62,  3,    17,   'Ghosts of Mortis',                'Mortis'),
  (63,  3,    18,   'The Citadel',                     'Citadel'),
  (64,  3,    19,   'Counter Attack',                  'Citadel'),
  (65,  3,    20,   'Citadel Rescue',                  'Citadel'),
  (66,  3,    21,   'Padawan Lost',                    'Trandoshan Hunters'),
  (67,  3,    22,   'Wookiee Hunt',                    'Trandoshan Hunters'),
  (68,  4,    1,    'Water War',                       'Battle of Mon Cala'),
  (69,  4,    2,    'Gungan Attack',                   'Battle of Mon Cala'),
  (70,  4,    3,    'Prisoners',                       'Battle of Mon Cala'),
  (71,  4,    4,    'Shadow Warrior',                  'Battle of Mon Cala'),
  (72,  4,    5,    'Mercy Mission',                   NULL),
  (73,  4,    6,    'Nomad Droids',                    NULL),
  (74,  4,    7,    'Darkness on Umbara',               'Umbara'),
  (75,  4,    8,    'The General',                     'Umbara'),
  (76,  4,    9,    'Plan of Dissent',                 'Umbara'),
  (77,  4,    10,   'Carnage of Krell',                'Umbara'),
  (78,  4,    11,   'Kidnapped',                       'Zygerrian Slavers'),
  (79,  4,    12,   'Slaves of the Republic',           'Zygerrian Slavers'),
  (80,  4,    13,   'Escape from Kadavo',               'Zygerrian Slavers'),
  (81,  4,    14,   'A Friend In Need',                NULL),
  (82,  4,    15,   'Deception',                       'Deception (Hardeen)'),
  (83,  4,    16,   'Friends and Enemies',              'Deception (Hardeen)'),
  (84,  4,    17,   'The Box',                         'Deception (Hardeen)'),
  (85,  4,    18,   'Crisis on Naboo',                 'Deception (Hardeen)'),
  (86,  4,    19,   'Massacre',                        'Nightsisters'),
  (87,  4,    20,   'Bounty',                          NULL),
  (88,  4,    21,   'Brothers',                        'Maul Returns'),
  (89,  4,    22,   'Revenge',                         'Maul Returns'),
  (90,  5,    2,    'A War on Two Fronts',              'Onderon'),
  (91,  5,    3,    'Front Runners',                   'Onderon'),
  (92,  5,    4,    'The Soft War',                    'Onderon'),
  (93,  5,    5,    'Tipping Points',                  'Onderon'),
  (94,  5,    6,    'The Gathering',                   'The Gathering'),
  (95,  5,    7,    'A Test of Strength',               'The Gathering'),
  (96,  5,    8,    'Bound for Rescue',                'The Gathering'),
  (97,  5,    9,    'A Necessary Bond',                'The Gathering'),
  (98,  5,    10,   'Secret Weapons',                  'D-Squad'),
  (99,  5,    11,   'A Sunny Day in the Void',          'D-Squad'),
  (100, 5,    12,   'Missing in Action',                'D-Squad'),
  (101, 5,    13,   'Point of No Return',               'D-Squad'),
  (102, 5,    1,    'Revival',                         'Shadow Collective'),
  (103, 5,    14,   'Eminence',                        'Shadow Collective'),
  (104, 5,    15,   'Shades of Reason',                'Shadow Collective'),
  (105, 5,    16,   'The Lawless',                     'Shadow Collective'),
  (106, 5,    17,   'Sabotage',                        'Wrong Jedi'),
  (107, 5,    18,   'The Jedi Who Knew Too Much',       'Wrong Jedi'),
  (108, 5,    19,   'To Catch a Jedi',                 'Wrong Jedi'),
  (109, 5,    20,   'The Wrong Jedi',                  'Wrong Jedi'),
  (110, 6,    1,    'The Unknown',                     'Fives'),
  (111, 6,    2,    'Conspiracy',                      'Fives'),
  (112, 6,    3,    'Fugitive',                        'Fives'),
  (113, 6,    4,    'Orders',                          'Fives'),
  (114, 6,    5,    'An Old Friend',                   'Rush Clovis'),
  (115, 6,    6,    'The Rise of Clovis',               'Rush Clovis'),
  (116, 6,    7,    'Crisis at the Heart',              'Rush Clovis'),
  (117, 6,    8,    'The Disappeared',                 'Bardotta'),
  (118, 6,    9,    'The Disappeared: Pt. II',          'Bardotta'),
  (119, 6,    10,   'The Lost One',                    'Yoda''s Path'),
  (120, 6,    11,   'Voices',                          'Yoda''s Path'),
  (121, 6,    12,   'Destiny',                         'Yoda''s Path'),
  (122, 6,    13,   'Sacrifice',                       'Yoda''s Path'),
  (123, 7,    5,    'Gone with a Trace',                'Martez Sisters'),
  (124, 7,    6,    'Deal No Deal',                    'Martez Sisters'),
  (125, 7,    7,    'Dangerous Debt',                  'Martez Sisters'),
  (126, 7,    8,    'Together Again',                  'Martez Sisters'),
  (127, 7,    1,    'The Bad Batch',                   'Bad Batch'),
  (128, 7,    2,    'A Distant Echo',                  'Bad Batch'),
  (129, 7,    3,    'On the Wings of Keeradaks',        'Bad Batch'),
  (130, 7,    4,    'Unfinished Business',              'Bad Batch'),
  (131, 7,    9,    'Old Friends Not Forgotten',        'Siege of Mandalore'),
  (132, 7,    10,   'The Phantom Apprentice',           'Siege of Mandalore'),
  (133, 7,    11,   'Shattered',                       'Siege of Mandalore'),
  (134, 7,    12,   'Victory and Death',                'Siege of Mandalore');
