## Deploys to FTP

##name: Deploy

##on:
##  push:
##    branches: [ "master" ]

##jobs:
##  web-deploy:
##    name: 🚀 Deploy
##    runs-on: ubuntu-latest
##    steps:
##    - name: 🚚 Get Latest Code
##      uses: actions/checkout@v3

##    - name: 📦 Install Packages
##      uses: actions/setup-node@v3
##      with:
##        node-version: 18
##        cache: "npm"
##    - run: npm ci
      
##    - name: 🔨 Build
##      run: npm run build
      
##    - name: 📂 Sync files
##      uses: SamKirkland/FTP-Deploy-Action@4.3.2
##      with:
##        server: ashercarlow.com
##        username: asher_ashercarlow
##       password: ${{ secrets.FTP_PASSWORD }}
##       server-dir: ~/
##        local-dir: dist/
